import { calculateComplianceSnapshot } from "@/lib/compliance-engine";
import { triggerDeceptionIncident } from "@/lib/deception-engine";
import { createSecurityEvent } from "@/lib/event-engine";
import { calculateAssetRisk } from "@/lib/risk-engine";
import { generateReports } from "@/lib/report-engine";
import { evaluateZeroTrustAccess } from "@/lib/zero-trust-engine";
import {
  AccessRequest,
  ArchitectureLayer,
  CloudMapLink,
  CloudMapNode,
  ControlItem,
  DataAsset,
  DeceptionAsset,
  DemoEnvironment,
  IdentityProfile,
  PolicyRule,
  SimulationScenario,
  ThreatItem,
  ThreatMatrixEntry,
} from "@/types";
import { makeId } from "@/lib/utils";

type AssetSeed = Omit<DataAsset, "risk">;

const now = "2026-05-05T10:30:00.000Z";

function withRisk(asset: AssetSeed): DataAsset {
  return {
    ...asset,
    risk: calculateAssetRisk({ ...asset, risk: undefined as never }),
  };
}

const identities: IdentityProfile[] = [
  {
    id: "id-ayse",
    name: "Ayse Demir",
    type: "user",
    role: "SOC Analisti",
    department: "Security Operations",
    homeLocation: "private_cloud",
    region: "TR-IST",
    mfaEnabled: true,
    deviceTrust: "trusted",
    anomalyScore: 18,
    riskScore: 24,
    status: "active",
    lastSeenAt: "2026-05-05T09:55:00.000Z",
    notes: ["Kritik olay triage akışlarını yürütüyor."],
  },
  {
    id: "id-zeynep",
    name: "Zeynep Acar",
    type: "user",
    role: "Cloud Platform Admin",
    department: "Cloud Operations",
    homeLocation: "private_cloud",
    region: "TR-IST",
    mfaEnabled: true,
    deviceTrust: "managed",
    anomalyScore: 25,
    riskScore: 34,
    status: "active",
    lastSeenAt: "2026-05-05T09:22:00.000Z",
    notes: ["Üretim IAM ve ağ politikalarını yönetiyor."],
  },
  {
    id: "id-emre",
    name: "Emre Kaya",
    type: "user",
    role: "BI Analyst",
    department: "Business Intelligence",
    homeLocation: "saas",
    region: "DE-FRA",
    mfaEnabled: false,
    deviceTrust: "unknown",
    anomalyScore: 67,
    riskScore: 69,
    status: "watchlist",
    lastSeenAt: "2026-05-05T04:56:00.000Z",
    notes: ["Mesai dışı export davranışı nedeniyle izleniyor."],
  },
  {
    id: "id-burak",
    name: "Burak Yildiz",
    type: "user",
    role: "Data Engineer",
    department: "Data Platform",
    homeLocation: "public_cloud",
    region: "TR-IST",
    mfaEnabled: true,
    deviceTrust: "managed",
    anomalyScore: 19,
    riskScore: 28,
    status: "active",
    lastSeenAt: "2026-05-05T08:30:00.000Z",
    notes: ["ETL ve feature store erişimleri var."],
  },
  {
    id: "id-selin",
    name: "Selin Dogan",
    type: "user",
    role: "Compliance Officer",
    department: "Governance",
    homeLocation: "private_cloud",
    region: "TR-ANK",
    mfaEnabled: true,
    deviceTrust: "trusted",
    anomalyScore: 11,
    riskScore: 18,
    status: "active",
    lastSeenAt: "2026-05-05T08:05:00.000Z",
    notes: ["KVKK ve GDPR görünürlüğünü yönetiyor."],
  },
  {
    id: "id-mert",
    name: "Mert Colak",
    type: "user",
    role: "Third-party Vendor Manager",
    department: "Procurement Security",
    homeLocation: "saas",
    region: "TR-IST",
    mfaEnabled: true,
    deviceTrust: "managed",
    anomalyScore: 22,
    riskScore: 31,
    status: "active",
    lastSeenAt: "2026-05-05T07:45:00.000Z",
    notes: ["Vendor entegrasyon izinlerini takip ediyor."],
  },
  {
    id: "id-finance-batch",
    name: "finance-batch-svc",
    type: "service",
    role: "Finance Batch Processor",
    department: "Finance Automation",
    homeLocation: "public_cloud",
    region: "US-EAST",
    mfaEnabled: false,
    deviceTrust: "unknown",
    anomalyScore: 76,
    riskScore: 74,
    status: "watchlist",
    lastSeenAt: "2026-05-05T03:38:00.000Z",
    notes: ["Beklenenden yüksek veri çekim hacmi gözlendi."],
  },
  {
    id: "id-backup",
    name: "backup-operator-svc",
    type: "service",
    role: "Backup Operator",
    department: "Infrastructure",
    homeLocation: "backup",
    region: "TR-ANK",
    mfaEnabled: true,
    deviceTrust: "trusted",
    anomalyScore: 13,
    riskScore: 19,
    status: "active",
    lastSeenAt: "2026-05-05T06:40:00.000Z",
    notes: ["Cold archive ve restore işlerini tetikliyor."],
  },
  {
    id: "id-vendor-api",
    name: "vendor-integration-api",
    type: "third_party",
    role: "Partner Connector",
    department: "Integrations",
    homeLocation: "saas",
    region: "US-WEST",
    mfaEnabled: false,
    deviceTrust: "unknown",
    anomalyScore: 63,
    riskScore: 66,
    status: "watchlist",
    lastSeenAt: "2026-05-05T02:54:00.000Z",
    notes: ["API tüketim profili olağan bandın üstünde."],
  },
  {
    id: "id-reporting",
    name: "reporting-export-svc",
    type: "service",
    role: "Reporting Exporter",
    department: "BI",
    homeLocation: "public_cloud",
    region: "EU-WEST",
    mfaEnabled: false,
    deviceTrust: "unknown",
    anomalyScore: 58,
    riskScore: 61,
    status: "watchlist",
    lastSeenAt: "2026-05-05T05:18:00.000Z",
    notes: ["Dışa aktarım kotası eşiğine yakın çalışıyor."],
  },
  {
    id: "id-security-admin",
    name: "security.admin",
    type: "user",
    role: "Security Administrator",
    department: "Security Operations",
    homeLocation: "private_cloud",
    region: "TR-IST",
    mfaEnabled: true,
    deviceTrust: "trusted",
    anomalyScore: 12,
    riskScore: 21,
    status: "active",
    lastSeenAt: "2026-05-05T09:48:00.000Z",
    notes: ["SOAR playbook ve kritik olay containment onaylarını yürütür."],
  },
  {
    id: "id-legacy-token",
    name: "legacy-api-token",
    type: "third_party",
    role: "Legacy Partner Token",
    department: "Integrations",
    homeLocation: "public_cloud",
    region: "US-CENTRAL",
    mfaEnabled: false,
    deviceTrust: "unknown",
    anomalyScore: 79,
    riskScore: 81,
    status: "suspicious",
    lastSeenAt: "2026-05-05T01:42:00.000Z",
    notes: ["Eski entegrasyon anahtarı olağan dışı kullanım paterni gösteriyor."],
  },
];

const assetSeeds: AssetSeed[] = [
  {
    id: "asset-customer-db",
    name: "customer-db",
    path: "private-cloud/customer-db",
    dataType: "Müşteri çekirdek kayıtları",
    location: "private_cloud",
    storageType: "database",
    classification: "critical",
    temperature: "hot",
    owner: "Data Governance",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["PII", "KVKK", "GDPR"],
    retentionPolicy: "5 yıl",
    anonymizationStatus: "partial",
    lastAccessedAt: "2026-05-05T09:12:00.000Z",
    accessCount24h: 118,
    accessIntensity: 88,
    findings: ["Dışa aktarım talepleri için step-up zorunlu."],
    recommendedControls: ["RBAC/ABAC", "MFA", "DLP"],
  },
  {
    id: "asset-analytics-bucket",
    name: "analytics-bucket",
    path: "public-cloud/analytics-bucket",
    dataType: "Analitik export datasetleri",
    location: "public_cloud",
    storageType: "object_storage",
    classification: "sensitive",
    temperature: "hot",
    owner: "BI Team",
    encryptionEnabled: false,
    kmsEnabled: false,
    backupEnabled: true,
    kvkkScope: false,
    gdprScope: true,
    privacyTags: ["GDPR", "Usage"],
    retentionPolicy: "12 ay",
    anonymizationStatus: "partial",
    lastAccessedAt: "2026-05-05T04:20:00.000Z",
    accessCount24h: 92,
    accessIntensity: 80,
    findings: ["Public cloud üzerinde şifreleme eksik."],
    recommendedControls: ["Encryption", "KMS", "CSPM"],
  },
  {
    id: "asset-finance-records",
    name: "finance-records",
    path: "private-cloud/finance-records",
    dataType: "Finans kayıtları",
    location: "private_cloud",
    storageType: "database",
    classification: "critical",
    temperature: "warm",
    owner: "Finance Security",
    encryptionEnabled: true,
    kmsEnabled: false,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["Financial", "KVKK", "GDPR"],
    retentionPolicy: "10 yıl",
    anonymizationStatus: "missing",
    lastAccessedAt: "2026-05-05T05:15:00.000Z",
    accessCount24h: 44,
    accessIntensity: 48,
    findings: ["KMS rotasyonu eksik."],
    recommendedControls: ["KMS", "Backup", "SIEM"],
  },
  {
    id: "asset-crm-export",
    name: "crm-export",
    path: "saas/crm-export",
    dataType: "CRM dışa aktarım arşivleri",
    location: "saas",
    storageType: "saas_export",
    classification: "sensitive",
    temperature: "warm",
    owner: "Sales Operations",
    encryptionEnabled: true,
    kmsEnabled: false,
    backupEnabled: false,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["CRM", "PII"],
    retentionPolicy: "18 ay",
    anonymizationStatus: "partial",
    lastAccessedAt: "2026-05-05T06:40:00.000Z",
    accessCount24h: 33,
    accessIntensity: 40,
    findings: ["Üçüncü taraf erişim denetimi sıkılaştırılmalı."],
    recommendedControls: ["CASB", "DLP", "MFA"],
  },
  {
    id: "asset-cold-archive",
    name: "cold-archive",
    path: "backup/cold-archive",
    dataType: "Soğuk arşiv snapshot",
    location: "backup",
    storageType: "backup_archive",
    classification: "confidential",
    temperature: "cold",
    owner: "Backup Team",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: false,
    privacyTags: ["Archive", "KVKK"],
    retentionPolicy: "7 yıl",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-01T09:00:00.000Z",
    accessCount24h: 6,
    accessIntensity: 8,
    findings: ["Restore tatbikatı güncellenmeli."],
    recommendedControls: ["Backup", "Secure Deletion"],
  },
  {
    id: "asset-hr-payroll-vault",
    name: "hr-payroll-vault",
    path: "private-cloud/hr-payroll-vault",
    dataType: "İK bordro dokümanları",
    location: "private_cloud",
    storageType: "file_share",
    classification: "critical",
    temperature: "warm",
    owner: "HR Security",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["HR", "PII"],
    retentionPolicy: "6 yıl",
    anonymizationStatus: "missing",
    lastAccessedAt: "2026-05-05T07:02:00.000Z",
    accessCount24h: 29,
    accessIntensity: 34,
    findings: ["Anonimleştirme iş akışı eksik."],
    recommendedControls: ["DLP", "RBAC/ABAC"],
  },
  {
    id: "asset-api-audit-logstore",
    name: "api-audit-logstore",
    path: "private-cloud/api-audit-logstore",
    dataType: "API audit kayıtları",
    location: "private_cloud",
    storageType: "object_storage",
    classification: "confidential",
    temperature: "hot",
    owner: "API Security",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Audit", "API"],
    retentionPolicy: "24 ay",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T09:20:00.000Z",
    accessCount24h: 81,
    accessIntensity: 74,
    findings: ["Immutable log storage genişletilmeli."],
    recommendedControls: ["SIEM", "Backup"],
  },
  {
    id: "asset-raw-ingest-zone",
    name: "raw-ingest-zone",
    path: "public-cloud/raw-ingest-zone",
    dataType: "Ham veri ingest alanı",
    location: "public_cloud",
    storageType: "object_storage",
    classification: "internal",
    temperature: "hot",
    owner: "Data Platform",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Telemetry"],
    retentionPolicy: "90 gün",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T08:58:00.000Z",
    accessCount24h: 104,
    accessIntensity: 83,
    findings: ["Resource consumption limiti izlenmeli."],
    recommendedControls: ["API Gateway", "CWPP"],
  },
  {
    id: "asset-pii-report-share",
    name: "pii-report-share",
    path: "private-cloud/pii-report-share",
    dataType: "PII rapor paylaşımları",
    location: "private_cloud",
    storageType: "file_share",
    classification: "sensitive",
    temperature: "warm",
    owner: "Governance",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["PII"],
    retentionPolicy: "24 ay",
    anonymizationStatus: "applied",
    lastAccessedAt: "2026-05-05T08:10:00.000Z",
    accessCount24h: 18,
    accessIntensity: 24,
    findings: ["Shared link süreleri kısaltılmalı."],
    recommendedControls: ["DLP", "IAM"],
  },
  {
    id: "asset-medical-claims-zone",
    name: "medical-claims-zone",
    path: "private-cloud/medical-claims-zone",
    dataType: "Sağlık provizyon talepleri",
    location: "private_cloud",
    storageType: "database",
    classification: "critical",
    temperature: "hot",
    owner: "Claims Security",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["Health", "PII"],
    retentionPolicy: "8 yıl",
    anonymizationStatus: "partial",
    lastAccessedAt: "2026-05-05T09:08:00.000Z",
    accessCount24h: 57,
    accessIntensity: 64,
    findings: ["Export işlemleri ek onay gerektiriyor."],
    recommendedControls: ["MFA", "RBAC/ABAC", "DLP"],
  },
  {
    id: "asset-vendor-sync-cache",
    name: "vendor-sync-cache",
    path: "saas/vendor-sync-cache",
    dataType: "Tedarikçi senkronizasyon cache",
    location: "saas",
    storageType: "saas_export",
    classification: "confidential",
    temperature: "warm",
    owner: "Vendor Management",
    encryptionEnabled: true,
    kmsEnabled: false,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: true,
    privacyTags: ["Vendor"],
    retentionPolicy: "Belirsiz",
    anonymizationStatus: "missing",
    lastAccessedAt: "2026-05-05T02:50:00.000Z",
    accessCount24h: 61,
    accessIntensity: 59,
    findings: ["Saklama süresi ve veri minimizasyonu net değil."],
    recommendedControls: ["CASB", "Secure Deletion", "SIEM"],
  },
  {
    id: "asset-secrets-vault",
    name: "secrets-vault",
    path: "private-cloud/secrets-vault",
    dataType: "Uygulama sırları ve token metadata",
    location: "private_cloud",
    storageType: "database",
    classification: "critical",
    temperature: "hot",
    owner: "Platform Security",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Secrets"],
    retentionPolicy: "12 ay",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T09:18:00.000Z",
    accessCount24h: 47,
    accessIntensity: 52,
    findings: ["Privileged access review sıklaştırılmalı."],
    recommendedControls: ["IAM", "MFA", "SIEM"],
  },
  {
    id: "asset-legal-hold-archive",
    name: "legal-hold-archive",
    path: "backup/legal-hold-archive",
    dataType: "Yasal bekletme arşivi",
    location: "backup",
    storageType: "backup_archive",
    classification: "confidential",
    temperature: "cold",
    owner: "Legal Operations",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["Legal", "Retention"],
    retentionPolicy: "Dava kapanana kadar",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-03T14:00:00.000Z",
    accessCount24h: 3,
    accessIntensity: 6,
    findings: ["İmha tetikleyicileri belgeye bağlı."],
    recommendedControls: ["Secure Deletion", "Backup"],
  },
  {
    id: "asset-mobile-usage-lake",
    name: "mobile-usage-lake",
    path: "public-cloud/mobile-usage-lake",
    dataType: "Mobil kullanım telemetrisi",
    location: "public_cloud",
    storageType: "object_storage",
    classification: "internal",
    temperature: "hot",
    owner: "Digital Analytics",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Telemetry"],
    retentionPolicy: "6 ay",
    anonymizationStatus: "applied",
    lastAccessedAt: "2026-05-05T09:04:00.000Z",
    accessCount24h: 98,
    accessIntensity: 78,
    findings: ["Rate limiting ve cost guardrail izlenmeli."],
    recommendedControls: ["CWPP", "API Gateway"],
  },
  {
    id: "asset-ml-feature-store",
    name: "ml-feature-store",
    path: "private-cloud/ml-feature-store",
    dataType: "ML feature özetleri",
    location: "private_cloud",
    storageType: "database",
    classification: "confidential",
    temperature: "hot",
    owner: "AI Platform",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["ML"],
    retentionPolicy: "180 gün",
    anonymizationStatus: "applied",
    lastAccessedAt: "2026-05-05T08:48:00.000Z",
    accessCount24h: 66,
    accessIntensity: 57,
    findings: ["Service account scope daraltılmalı."],
    recommendedControls: ["RBAC/ABAC", "SIEM"],
  },
  {
    id: "asset-tokenized-customer-view",
    name: "tokenized-customer-view",
    path: "private-cloud/tokenized-customer-view",
    dataType: "Tokenize müşteri görünümü",
    location: "private_cloud",
    storageType: "database",
    classification: "sensitive",
    temperature: "warm",
    owner: "Data Governance",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["Tokenization", "PII"],
    retentionPolicy: "24 ay",
    anonymizationStatus: "applied",
    lastAccessedAt: "2026-05-05T07:16:00.000Z",
    accessCount24h: 25,
    accessIntensity: 28,
    findings: ["İyi durumda, düzenli erişim gözden geçirmesi yeterli."],
    recommendedControls: ["RBAC/ABAC", "DLP"],
  },
  {
    id: "asset-backup-finance-snapshot",
    name: "backup-finance-snapshot",
    path: "backup/backup-finance-snapshot",
    dataType: "Finans snapshot yedeği",
    location: "backup",
    storageType: "backup_archive",
    classification: "sensitive",
    temperature: "cold",
    owner: "Infrastructure",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: true,
    gdprScope: false,
    privacyTags: ["Finance"],
    retentionPolicy: "7 yıl",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-04T11:20:00.000Z",
    accessCount24h: 7,
    accessIntensity: 9,
    findings: ["Air-gap restore başarı metriği eklenmeli."],
    recommendedControls: ["Backup", "Secure Deletion"],
  },
  {
    id: "asset-hr-onboarding",
    name: "hr-onboarding",
    path: "saas/hr-onboarding",
    dataType: "İşe alım onboarding verileri",
    location: "saas",
    storageType: "saas_export",
    classification: "sensitive",
    temperature: "warm",
    owner: "HR Operations",
    encryptionEnabled: true,
    kmsEnabled: false,
    backupEnabled: false,
    kvkkScope: true,
    gdprScope: true,
    privacyTags: ["PII", "HR"],
    retentionPolicy: "24 ay",
    anonymizationStatus: "partial",
    lastAccessedAt: "2026-05-05T07:54:00.000Z",
    accessCount24h: 21,
    accessIntensity: 26,
    findings: ["SaaS connector izinleri minimize edilmeli."],
    recommendedControls: ["CASB", "MFA"],
  },
  {
    id: "asset-public-marketing-cdn",
    name: "public-marketing-cdn",
    path: "public-cloud/public-marketing-cdn",
    dataType: "Pazarlama statik içeriği",
    location: "public_cloud",
    storageType: "object_storage",
    classification: "public",
    temperature: "hot",
    owner: "Marketing",
    encryptionEnabled: false,
    kmsEnabled: false,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Public"],
    retentionPolicy: "90 gün",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T09:25:00.000Z",
    accessCount24h: 200,
    accessIntensity: 96,
    findings: ["Public içerik olduğu için düşük veri riski, ancak cost kontrolü önemli."],
    recommendedControls: ["API Gateway", "CWPP"],
  },
  {
    id: "asset-governance-register",
    name: "governance-register",
    path: "private-cloud/governance-register",
    dataType: "Veri işleme envanteri",
    location: "private_cloud",
    storageType: "database",
    classification: "internal",
    temperature: "warm",
    owner: "Governance",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Governance"],
    retentionPolicy: "Sürekli",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T08:15:00.000Z",
    accessCount24h: 12,
    accessIntensity: 18,
    findings: ["Politika sürüm kayıtları backend ile desteklenmeli."],
    recommendedControls: ["IAM", "SIEM"],
  },
  {
    id: "asset-third-party-contracts",
    name: "third-party-contracts",
    path: "private-cloud/third-party-contracts",
    dataType: "Tedarikçi sözleşmeleri",
    location: "private_cloud",
    storageType: "file_share",
    classification: "confidential",
    temperature: "warm",
    owner: "Procurement",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: true,
    kvkkScope: false,
    gdprScope: true,
    privacyTags: ["Vendor", "Contract"],
    retentionPolicy: "5 yıl",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T06:15:00.000Z",
    accessCount24h: 16,
    accessIntensity: 19,
    findings: ["Cross-border transfer etiketleri düzenli doğrulanmalı."],
    recommendedControls: ["CASB", "SIEM"],
  },
  {
    id: "asset-ops-telemetry",
    name: "ops-telemetry",
    path: "public-cloud/ops-telemetry",
    dataType: "Operasyon telemetrisi",
    location: "public_cloud",
    storageType: "object_storage",
    classification: "internal",
    temperature: "hot",
    owner: "Platform Ops",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Telemetry"],
    retentionPolicy: "30 gün",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: "2026-05-05T09:10:00.000Z",
    accessCount24h: 144,
    accessIntensity: 90,
    findings: ["Visibility gap senaryoları için loglama kontrol edilmeli."],
    recommendedControls: ["SIEM", "CWPP"],
  },
  {
    id: "asset-admin-secrets-bucket",
    name: "admin-secrets-bucket",
    path: "deception/admin-secrets-bucket",
    dataType: "Sahte yönetim sırları deposu",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "hot",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 2,
    accessIntensity: 4,
    findings: ["Gerçek veri içermez, yalnızca aldatma amaçlıdır."],
    recommendedControls: ["Deception", "SIEM", "SOAR"],
    isDeception: true,
  },
  {
    id: "asset-legacy-finance-backup",
    name: "legacy-finance-backup",
    path: "deception/legacy-finance-backup",
    dataType: "Sahte legacy finans yedeği",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "cold",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 1,
    accessIntensity: 2,
    findings: ["Gerçek veri içermez."],
    recommendedControls: ["Deception", "SOAR"],
    isDeception: true,
  },
  {
    id: "asset-kvkk-sensitive-copy",
    name: "kvkk-sensitive-copy",
    path: "deception/kvkk-sensitive-copy",
    dataType: "Sahte KVKK veri kopyası",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "warm",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 0,
    accessIntensity: 1,
    findings: ["Regülasyon temalı deceptive lure."],
    recommendedControls: ["Deception", "SIEM"],
    isDeception: true,
  },
  {
    id: "asset-shadow-api-logs",
    name: "shadow-api-logs",
    path: "deception/shadow-api-logs",
    dataType: "Sahte shadow API logları",
    location: "deception",
    storageType: "deception_storage",
    classification: "confidential",
    temperature: "warm",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 0,
    accessIntensity: 2,
    findings: ["Lateral movement keşfi için kullanılır."],
    recommendedControls: ["Deception", "SIEM"],
    isDeception: true,
  },
  {
    id: "asset-payroll-2026-dump",
    name: "payroll-2026-dump",
    path: "deception/payroll-2026-dump",
    dataType: "Sahte payroll dump",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "warm",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 0,
    accessIntensity: 1,
    findings: ["İç tehdit dikkatini çekmek için adlandırıldı."],
    recommendedControls: ["Deception", "SOAR"],
    isDeception: true,
  },
  {
    id: "asset-old-root-token-store",
    name: "old-root-token-store",
    path: "deception/old-root-token-store",
    dataType: "Sahte eski root token store",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "hot",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 1,
    accessIntensity: 3,
    findings: ["Yüksek cazibeli privilege escalation tuzağı."],
    recommendedControls: ["Deception", "SOAR"],
    isDeception: true,
  },
  {
    id: "asset-customer-archive-decoy",
    name: "fake-customer-archive",
    path: "deception/fake-customer-archive",
    dataType: "Sahte müşteri arşivi",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "cold",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 0,
    accessIntensity: 1,
    findings: ["Arşiv odaklı veri keşfi için lure görevi görür."],
    recommendedControls: ["Deception", "SIEM"],
    isDeception: true,
  },
  {
    id: "asset-legacy-customer-db-shadow",
    name: "legacy-customer-db-shadow",
    path: "deception/legacy-customer-db-shadow",
    dataType: "Sahte legacy müşteri veritabanı",
    location: "deception",
    storageType: "deception_storage",
    classification: "critical",
    temperature: "warm",
    owner: "Active Defense Lab",
    encryptionEnabled: true,
    kmsEnabled: true,
    backupEnabled: false,
    kvkkScope: false,
    gdprScope: false,
    privacyTags: ["Deception", "Database"],
    retentionPolicy: "N/A",
    anonymizationStatus: "not_applicable",
    lastAccessedAt: now,
    accessCount24h: 0,
    accessIntensity: 1,
    findings: ["Gerçek veri içermez; sahte veritabanı tuzağı olarak kullanılır."],
    recommendedControls: ["Deception", "SOAR", "SIEM"],
    isDeception: true,
  },
];

const assets = assetSeeds.map(withRisk);

const deceptions: DeceptionAsset[] = [
  {
    id: "dec-1",
    name: "admin-secrets-bucket",
    location: "deception",
    description: "Gerçek veri içermez; saldırganı yüksek değerli sırlar algısıyla çekmek için tasarlanmıştır.",
    realData: false,
    containsRealData: false,
    fakeType: "bucket",
    lureScore: 95,
    triggerCount: 1,
    lastTriggeredAt: "2026-05-05T03:40:00.000Z",
    mappedThreat: "Credential Theft",
    severity: "critical",
    recommendedResponse: "Kimliği izole et ve token iptal et.",
    status: "triggered",
    autoActions: ["isolate_identity", "revoke_token", "notify_security_team"],
  },
  {
    id: "dec-2",
    name: "legacy-finance-backup",
    location: "deception",
    description: "Eski finans arşivi gibi görünen sahte backup hedefi.",
    realData: false,
    containsRealData: false,
    fakeType: "log_archive",
    lureScore: 88,
    triggerCount: 0,
    mappedThreat: "Insider Threat",
    severity: "high",
    recommendedResponse: "Erişimi ilişkilendir ve olay oluştur.",
    status: "armed",
    autoActions: ["create_ticket", "notify_security_team"],
  },
  {
    id: "dec-3",
    name: "kvkk-sensitive-copy",
    location: "deception",
    description: "Regülasyon hassas veri algısı yaratır, gerçek veri içermez.",
    realData: false,
    containsRealData: false,
    fakeType: "database",
    lureScore: 90,
    triggerCount: 0,
    mappedThreat: "Non-compliant Transfer",
    severity: "critical",
    recommendedResponse: "Actor profilini şüpheli işaretle.",
    status: "armed",
    autoActions: ["isolate_identity", "create_ticket"],
  },
  {
    id: "dec-4",
    name: "shadow-api-logs",
    location: "deception",
    description: "API keşif ve SSRF benzeri davranışları erkenden fark etmeyi amaçlar.",
    realData: false,
    containsRealData: false,
    fakeType: "api",
    lureScore: 78,
    triggerCount: 0,
    mappedThreat: "API Abuse",
    severity: "high",
    recommendedResponse: "API kaynağını ve tokeni incelemeye al.",
    status: "armed",
    autoActions: ["revoke_token", "notify_security_team"],
  },
  {
    id: "dec-5",
    name: "payroll-2026-dump",
    location: "deception",
    description: "İç tehdit ve ayrıcalık ihlallerini cezbetmek için adlandırılmış tuzak alan.",
    realData: false,
    containsRealData: false,
    fakeType: "database",
    lureScore: 84,
    triggerCount: 0,
    mappedThreat: "Insider Threat",
    severity: "critical",
    recommendedResponse: "Kimliği izole et ve HR/security koordinasyonu başlat.",
    status: "armed",
    autoActions: ["isolate_identity", "notify_security_team"],
  },
  {
    id: "dec-6",
    name: "old-root-token-store",
    location: "deception",
    description: "Privilege escalation niyeti gösteren aktörleri ayıklamak için oluşturuldu.",
    realData: false,
    containsRealData: false,
    fakeType: "token_store",
    lureScore: 97,
    triggerCount: 0,
    mappedThreat: "Privilege Escalation",
    severity: "critical",
    recommendedResponse: "Account lock ve token revoke uygula.",
    status: "armed",
    autoActions: ["account_lock", "revoke_token", "notify_security_team"],
  },
  {
    id: "dec-7",
    name: "fake-customer-archive",
    location: "deception",
    description: "Arşiv odaklı veri keşif girişimlerini yönlendiren honeypot depo.",
    realData: false,
    containsRealData: false,
    fakeType: "log_archive",
    lureScore: 73,
    triggerCount: 0,
    mappedThreat: "Limited Visibility",
    severity: "medium",
    recommendedResponse: "Erişim kaynağını korelasyonla incele.",
    status: "armed",
    autoActions: ["create_ticket", "notify_security_team"],
  },
  {
    id: "dec-8",
    name: "crm-admin-export-shadow",
    location: "deception",
    description: "SaaS export akışları etrafında davranış analizi için kullanılır.",
    realData: false,
    containsRealData: false,
    fakeType: "api",
    lureScore: 80,
    triggerCount: 0,
    mappedThreat: "Third Party Risk",
    severity: "high",
    recommendedResponse: "Third-party erişim kapsamını daralt.",
    status: "armed",
    autoActions: ["revoke_token", "create_ticket"],
  },
  {
    id: "dec-9",
    name: "legacy-customer-db-shadow",
    location: "deception",
    description: "Gerçek veri içermeyen, eski müşteri veritabanı gibi görünen sahte veritabanı tuzağı.",
    realData: false,
    containsRealData: false,
    fakeType: "database",
    lureScore: 96,
    triggerCount: 0,
    mappedThreat: "Credential Theft",
    severity: "critical",
    recommendedResponse: "Kimliği izole et, tokeni iptal et ve deception incident raporu oluştur.",
    status: "armed",
    autoActions: ["isolate_identity", "revoke_token", "create_ticket", "notify_security_team"],
  },
];

function decisionToStatus(decision: AccessRequest["evaluation"]["decision"]): AccessRequest["status"] {
  switch (decision) {
    case "allow":
    case "limited_allow":
      return "approved";
    case "require_step_up_auth":
      return "step_up";
    case "deny":
      return "rejected";
    case "isolate":
      return "isolated";
  }
}

function buildAccessRequest(input: {
  id: string;
  identityId: string;
  targetAssetId: string;
  sourceLocation: AccessRequest["sourceLocation"];
  sourceRegion: string;
  deviceTrust: AccessRequest["deviceTrust"];
  requestTime: string;
  requestedAction: AccessRequest["requestedAction"];
  mfa: boolean;
  locationRisk: AccessRequest["locationRisk"];
  timeRisk: AccessRequest["timeRisk"];
  pending?: boolean;
}): AccessRequest {
  const identity = identities.find((entry) => entry.id === input.identityId);
  const asset = assets.find((entry) => entry.id === input.targetAssetId);

  if (!identity || !asset) {
    throw new Error("Mock request references missing identity or asset.");
  }

  const evaluation = evaluateZeroTrustAccess({
    identityVerified: identity.status !== "isolated",
    deviceTrust: input.deviceTrust,
    mfa: input.mfa,
    role: identity.role,
    requestedAction: input.requestedAction,
    dataSensitivity: asset.classification,
    locationRisk: input.locationRisk,
    timeRisk: input.timeRisk,
    isServiceAccount: identity.type !== "user",
    anomalyScore: identity.anomalyScore,
    targetLocation: asset.location,
    isDeceptionTarget: asset.isDeception,
  });

  return {
    id: input.id,
    identityId: identity.id,
    identityName: identity.name,
    identityType: identity.type,
    role: identity.role,
    targetAssetId: asset.id,
    targetAssetName: asset.name,
    sourceLocation: input.sourceLocation,
    sourceRegion: input.sourceRegion,
    deviceTrust: input.deviceTrust,
    requestTime: input.requestTime,
    requestedAction: input.requestedAction,
    mfa: input.mfa,
    anomalyScore: identity.anomalyScore,
    locationRisk: input.locationRisk,
    timeRisk: input.timeRisk,
    dataSensitivity: asset.classification,
    evaluation,
    status: input.pending ? "pending" : decisionToStatus(evaluation.decision),
  };
}

const accessRequests: AccessRequest[] = [
  buildAccessRequest({
    id: "req-1",
    identityId: "id-ayse",
    targetAssetId: "asset-api-audit-logstore",
    sourceLocation: "private_cloud",
    sourceRegion: "TR-IST",
    deviceTrust: "trusted",
    requestTime: "2026-05-05T09:55:00.000Z",
    requestedAction: "read",
    mfa: true,
    locationRisk: "low",
    timeRisk: "normal",
  }),
  buildAccessRequest({
    id: "req-2",
    identityId: "id-emre",
    targetAssetId: "asset-customer-db",
    sourceLocation: "saas",
    sourceRegion: "DE-FRA",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T04:58:00.000Z",
    requestedAction: "export",
    mfa: false,
    locationRisk: "high",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-3",
    identityId: "id-zeynep",
    targetAssetId: "asset-secrets-vault",
    sourceLocation: "private_cloud",
    sourceRegion: "TR-IST",
    deviceTrust: "managed",
    requestTime: "2026-05-05T09:10:00.000Z",
    requestedAction: "admin",
    mfa: true,
    locationRisk: "low",
    timeRisk: "elevated",
  }),
  buildAccessRequest({
    id: "req-4",
    identityId: "id-finance-batch",
    targetAssetId: "asset-finance-records",
    sourceLocation: "public_cloud",
    sourceRegion: "US-EAST",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T03:30:00.000Z",
    requestedAction: "read",
    mfa: false,
    locationRisk: "medium",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-5",
    identityId: "id-vendor-api",
    targetAssetId: "asset-crm-export",
    sourceLocation: "saas",
    sourceRegion: "US-WEST",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T02:55:00.000Z",
    requestedAction: "write",
    mfa: false,
    locationRisk: "high",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-6",
    identityId: "id-reporting",
    targetAssetId: "asset-analytics-bucket",
    sourceLocation: "public_cloud",
    sourceRegion: "EU-WEST",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T05:12:00.000Z",
    requestedAction: "export",
    mfa: false,
    locationRisk: "medium",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-7",
    identityId: "id-burak",
    targetAssetId: "asset-raw-ingest-zone",
    sourceLocation: "public_cloud",
    sourceRegion: "TR-IST",
    deviceTrust: "managed",
    requestTime: "2026-05-05T08:40:00.000Z",
    requestedAction: "write",
    mfa: true,
    locationRisk: "low",
    timeRisk: "normal",
  }),
  buildAccessRequest({
    id: "req-8",
    identityId: "id-selin",
    targetAssetId: "asset-governance-register",
    sourceLocation: "private_cloud",
    sourceRegion: "TR-ANK",
    deviceTrust: "trusted",
    requestTime: "2026-05-05T08:12:00.000Z",
    requestedAction: "read",
    mfa: true,
    locationRisk: "low",
    timeRisk: "normal",
  }),
  buildAccessRequest({
    id: "req-9",
    identityId: "id-mert",
    targetAssetId: "asset-third-party-contracts",
    sourceLocation: "saas",
    sourceRegion: "TR-IST",
    deviceTrust: "managed",
    requestTime: "2026-05-05T07:48:00.000Z",
    requestedAction: "read",
    mfa: true,
    locationRisk: "medium",
    timeRisk: "normal",
    pending: true,
  }),
  buildAccessRequest({
    id: "req-10",
    identityId: "id-finance-batch",
    targetAssetId: "asset-admin-secrets-bucket",
    sourceLocation: "public_cloud",
    sourceRegion: "US-EAST",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T03:40:00.000Z",
    requestedAction: "read",
    mfa: false,
    locationRisk: "high",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-11",
    identityId: "id-vendor-api",
    targetAssetId: "asset-shadow-api-logs",
    sourceLocation: "saas",
    sourceRegion: "US-WEST",
    deviceTrust: "unknown",
    requestTime: "2026-05-05T03:05:00.000Z",
    requestedAction: "read",
    mfa: false,
    locationRisk: "high",
    timeRisk: "off_hours",
  }),
  buildAccessRequest({
    id: "req-12",
    identityId: "id-backup",
    targetAssetId: "asset-cold-archive",
    sourceLocation: "backup",
    sourceRegion: "TR-ANK",
    deviceTrust: "trusted",
    requestTime: "2026-05-05T06:42:00.000Z",
    requestedAction: "read",
    mfa: true,
    locationRisk: "low",
    timeRisk: "normal",
  }),
];

const eventSeeds = [
  createSecurityEvent({
    title: "Mesai dışı kritik veri export denemesi",
    severity: "high",
    category: "suspicious_export",
    source: "Emre Kaya",
    target: "customer-db",
    timestamp: "2026-05-05T04:59:00.000Z",
    description: "Kritik müşteri verisine MFA olmadan export erişimi denendi.",
    relatedControl: "Zero Trust + DLP",
    recommendation: "Step-up auth veya deny kararı uygula.",
    status: "investigating",
    evidence: ["Action: export", "Time risk: off_hours", "MFA: false"],
  }),
  createSecurityEvent({
    title: "Public cloud hassas veri şifreleme açığı",
    severity: "critical",
    category: "missing_encryption",
    source: "CSPM",
    target: "analytics-bucket",
    timestamp: "2026-05-05T06:20:00.000Z",
    description: "Genel bulutta şifrelenmemiş hassas veri tespit edildi.",
    relatedControl: "Encryption + KMS + CSPM",
    recommendation: "Encryption ve KMS zorunlu hale getirilmeli.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Üçüncü taraf API davranış anomalisi",
    severity: "high",
    category: "third_party_anomaly",
    source: "vendor-integration-api",
    target: "crm-export",
    timestamp: "2026-05-05T02:54:00.000Z",
    description: "Partner API anahtarı olağan profilin üstünde çağrı yaptı.",
    relatedControl: "API Gateway + CASB + SOAR",
    recommendation: "Token revoke ve kapsam daraltma önerilir.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Visibility gap: log agent kapalı",
    severity: "medium",
    category: "visibility_gap",
    source: "Telemetry Monitor",
    target: "ops-telemetry",
    timestamp: "2026-05-05T07:18:00.000Z",
    description: "Bir kaynakta loglama ajanı geçici olarak kapanmış görünüyor.",
    relatedControl: "SIEM + CWPP",
    recommendation: "Log forwarding agent yeniden başlatılmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Broken object level authorization sinyali",
    severity: "high",
    category: "unauthorized_access_attempt",
    source: "reporting-export-svc",
    target: "finance-records",
    timestamp: "2026-05-05T05:16:00.000Z",
    description: "Yetki dışı finans nesnesi erişim denemesi gözlendi.",
    relatedControl: "RBAC/ABAC + API Gateway",
    recommendation: "İsteği deny et ve service scope'u daralt.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Unrestricted resource consumption göstergesi",
    severity: "medium",
    category: "api_abuse",
    source: "reporting-export-svc",
    target: "raw-ingest-zone",
    timestamp: "2026-05-05T05:22:00.000Z",
    description: "Kaynak tüketim eşiği aşılmaya yaklaştı.",
    relatedControl: "API Gateway + CWPP",
    recommendation: "Rate limiting ve quota enforcement artırılmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Impossible travel uyarısı",
    severity: "medium",
    category: "impossible_travel",
    source: "Emre Kaya",
    target: "crm-export",
    timestamp: "2026-05-05T05:05:00.000Z",
    description: "Kısa sürede iki farklı bölgeden erişim denemesi görüldü.",
    relatedControl: "IAM + SIEM",
    recommendation: "Session challenge ve MFA uygulanmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Şifrelenmemiş SaaS export bulgusu",
    severity: "high",
    category: "missing_encryption",
    source: "SaaS Guardrail",
    target: "vendor-sync-cache",
    timestamp: "2026-05-05T03:10:00.000Z",
    description: "SaaS export cache için KMS karşılığı bir anahtar yönetimi bulunmuyor.",
    relatedControl: "CASB + Encryption",
    recommendation: "SaaS tarafı encryption posture güçlendirilmeli.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Public bucket exposure denemesi",
    severity: "medium",
    category: "public_bucket_detected",
    source: "Cloud Posture Monitor",
    target: "public-marketing-cdn",
    timestamp: "2026-05-05T08:22:00.000Z",
    description: "Public bucket policy beklenenden geniş izinler içeriyor.",
    relatedControl: "CSPM",
    recommendation: "Bucket policy daraltılmalı.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Privilege escalation davranış sinyali",
    severity: "high",
    category: "privilege_escalation",
    source: "finance-batch-svc",
    target: "secrets-vault",
    timestamp: "2026-05-05T03:26:00.000Z",
    description: "Servis hesabı normal rol sınırları dışında yetki aradı.",
    relatedControl: "IAM + Zero Trust",
    recommendation: "Servis hesabını karantinaya al.",
    status: "contained",
  }),
  createSecurityEvent({
    title: "Policy violation: critical data no MFA",
    severity: "high",
    category: "policy_violation",
    source: "Zero Trust Policy Engine",
    target: "customer-db",
    timestamp: "2026-05-05T05:00:00.000Z",
    description: "Kritik veriye MFA olmadan erişim kuralı ihlal edildi.",
    relatedControl: "MFA + Zero Trust",
    recommendation: "Talebi deny et ve kullanıcıyı challenge et.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Ransomware davranış göstergesi",
    severity: "critical",
    category: "ransomware_indicator",
    source: "EDR Telemetry",
    target: "finance-records",
    timestamp: "2026-05-05T06:48:00.000Z",
    description: "Kısa sürede yoğun dosya değişiklik paterni görüldü.",
    relatedControl: "EDR + Backup + SOAR",
    recommendation: "Kaynağı izole et ve restore planını hazırla.",
    status: "contained",
  }),
  createSecurityEvent({
    title: "Unsafe API consumption uyarısı",
    severity: "medium",
    category: "third_party_anomaly",
    source: "API Security Monitor",
    target: "vendor-sync-cache",
    timestamp: "2026-05-05T07:06:00.000Z",
    description: "Harici API yanıt doğrulaması zayıf bir iş akışında tüketiliyor.",
    relatedControl: "API Gateway + CASB",
    recommendation: "Schema validation ve supplier allowlist eklenmeli.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Public analytics export policy deviation",
    severity: "high",
    category: "policy_violation",
    source: "DLP",
    target: "analytics-bucket",
    timestamp: "2026-05-05T04:30:00.000Z",
    description: "Analytics export politikası beklenenden geniş aktarma izni taşıyor.",
    relatedControl: "DLP + CSPM",
    recommendation: "Export path kısıtlanmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Log retention policy drift",
    severity: "low",
    category: "visibility_gap",
    source: "Governance Monitor",
    target: "api-audit-logstore",
    timestamp: "2026-05-05T08:36:00.000Z",
    description: "Log saklama süresi politika ile birebir örtüşmüyor.",
    relatedControl: "SIEM + Governance",
    recommendation: "Retention policy düzeltmesi planlanmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "Cross-border transfer review pending",
    severity: "medium",
    category: "third_party_anomaly",
    source: "Compliance Layer",
    target: "third-party-contracts",
    timestamp: "2026-05-05T07:32:00.000Z",
    description: "Yurt dışı aktarım riski olan veri akışı inceleme bekliyor.",
    relatedControl: "CASB + Governance",
    recommendation: "Aktarım kayıtları ve kontrat koşulları gözden geçirilmeli.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Stale service account behavior",
    severity: "high",
    category: "api_abuse",
    source: "finance-batch-svc",
    target: "analytics-bucket",
    timestamp: "2026-05-05T03:18:00.000Z",
    description: "Eski servis hesabı anormal API kullanımı sergiledi.",
    relatedControl: "IAM + API Gateway",
    recommendation: "Token yenile ve scope azalt.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Backup verification overdue",
    severity: "medium",
    category: "policy_violation",
    source: "Backup Control",
    target: "cold-archive",
    timestamp: "2026-05-05T08:58:00.000Z",
    description: "Yedek doğrulama tatbikatı SLA dışına çıktı.",
    relatedControl: "Backup + Recover",
    recommendation: "Restore testi planlanmalı.",
    status: "open",
  }),
  createSecurityEvent({
    title: "CRM export DLP alert",
    severity: "high",
    category: "suspicious_export",
    source: "DLP",
    target: "crm-export",
    timestamp: "2026-05-05T07:20:00.000Z",
    description: "CRM export paketinde hassas alanlar tespit edildi.",
    relatedControl: "DLP + Zero Trust",
    recommendation: "Export paketini daralt ve onay akışı başlat.",
    status: "investigating",
  }),
  createSecurityEvent({
    title: "Service identity unusual token request",
    severity: "medium",
    category: "policy_violation",
    source: "IAM",
    target: "reporting-export-svc",
    timestamp: "2026-05-05T05:26:00.000Z",
    description: "Servis hesabı olağan dışı yetki kapsamı talep etti.",
    relatedControl: "IAM",
    recommendation: "Token policy gözden geçirilmeli.",
    status: "open",
  }),
];

const seededDeception = triggerDeceptionIncident({
  actor: identities.find((entry) => entry.id === "id-finance-batch")!,
  deception: deceptions.find((entry) => entry.name === "admin-secrets-bucket")!,
  timestamp: "2026-05-05T03:40:00.000Z",
});

const seededIdentities = identities.map((identity) =>
  identity.id === seededDeception.updatedIdentity.id ? seededDeception.updatedIdentity : identity,
);

const seededDeceptions = deceptions.map((deception) =>
  deception.id === seededDeception.updatedDeception.id ? seededDeception.updatedDeception : deception,
);

const events = [seededDeception.event, ...eventSeeds];

const policyRules: PolicyRule[] = [
  {
    id: "rule-1",
    name: "Kritik veriye MFA olmadan erişim reddedilir",
    description: "Critical sınıftaki veri için MFA false ise deny kararı üretilir.",
    enabled: true,
    owner: "Policy Engine",
    defaultDecision: "deny",
    severity: "high",
    conditions: ["classification=critical", "mfa=false"],
    actions: ["deny", "create_ticket"],
  },
  {
    id: "rule-2",
    name: "Riskli export işlemleri step-up ister",
    description: "Export ve yüksek risk skoru birleşirse ek kimlik doğrulama istenir.",
    enabled: true,
    owner: "Policy Engine",
    defaultDecision: "require_step_up_auth",
    severity: "medium",
    conditions: ["requestedAction=export", "riskScore>55"],
    actions: ["require_mfa", "notify_security_team"],
  },
  {
    id: "rule-3",
    name: "Deception varlığına erişim kritik alarm üretir",
    description: "Deception hedefe erişim isolate kararı ve kritik event üretir.",
    enabled: true,
    owner: "Policy Enforcement Point",
    defaultDecision: "isolate",
    severity: "critical",
    conditions: ["targetLocation=deception"],
    actions: ["isolate_identity", "revoke_token", "notify_security_team"],
  },
  {
    id: "rule-4",
    name: "Şüpheli servis hesabı izole edilir",
    description: "Servis hesabı anomali skoru 75 üstünde ise izolasyon önerilir.",
    enabled: true,
    owner: "Policy Administrator",
    defaultDecision: "isolate",
    severity: "high",
    conditions: ["identityType=service", "anomalyScore>=75"],
    actions: ["isolate_identity", "create_ticket"],
  },
  {
    id: "rule-5",
    name: "Şifrelenmemiş hassas veri kritik bulgu üretir",
    description: "Sensitive veya critical veri encryption yoksa kritik olay açılır.",
    enabled: true,
    owner: "Compliance Layer",
    defaultDecision: "deny",
    severity: "critical",
    conditions: ["classification in [sensitive,critical]", "encryption=false"],
    actions: ["create_ticket", "notify_security_team"],
  },
  {
    id: "rule-6",
    name: "Üçüncü taraf API anomalisinde token revoke öner",
    description: "Third-party anomali durumunda revoke_token önerilir.",
    enabled: true,
    owner: "Policy Administrator",
    defaultDecision: "deny",
    severity: "high",
    conditions: ["identityType=third_party", "anomalyScore>60"],
    actions: ["revoke_token", "create_ticket"],
  },
];

const layers: ArchitectureLayer[] = [
  {
    id: "layer-1",
    name: "Identity & Access",
    health: 84,
    detail: "IAM, MFA ve sürekli doğrulama akışı birlikte çalışıyor.",
  },
  {
    id: "layer-2",
    name: "Zero Trust Enforcement",
    health: 79,
    detail: "Policy Engine, Policy Administrator ve PEP karar üretimini görünür kılıyor.",
  },
  {
    id: "layer-3",
    name: "Data Protection",
    health: 73,
    detail: "Şifreleme ve KMS güçlü, fakat public cloud ve SaaS tarafında açıklar var.",
  },
  {
    id: "layer-4",
    name: "Detection & Response",
    health: 81,
    detail: "SIEM/SOAR olay akışı ve playbook zinciri simüle ediliyor.",
  },
  {
    id: "layer-5",
    name: "Active Defense",
    health: 89,
    detail: "Deception storage ve adversary engagement görünürlüğü güçlü.",
  },
];

const threats: ThreatItem[] = [
  { id: "th-1", name: "Misconfiguration" },
  { id: "th-2", name: "Credential Theft" },
  { id: "th-3", name: "API Abuse" },
  { id: "th-4", name: "Third Party Risk" },
  { id: "th-5", name: "Insider Threat" },
  { id: "th-6", name: "APT" },
  { id: "th-7", name: "Ransomware" },
  { id: "th-8", name: "Limited Visibility" },
  { id: "th-9", name: "Non-compliant Transfer" },
];

const controls: ControlItem[] = [
  { id: "ctl-1", name: "IAM" },
  { id: "ctl-2", name: "MFA" },
  { id: "ctl-3", name: "RBAC/ABAC" },
  { id: "ctl-4", name: "Encryption" },
  { id: "ctl-5", name: "KMS" },
  { id: "ctl-6", name: "DLP" },
  { id: "ctl-7", name: "Microsegmentation" },
  { id: "ctl-8", name: "API Gateway" },
  { id: "ctl-9", name: "SIEM" },
  { id: "ctl-10", name: "SOAR" },
  { id: "ctl-11", name: "CSPM" },
  { id: "ctl-12", name: "CWPP" },
  { id: "ctl-13", name: "CASB" },
  { id: "ctl-14", name: "Deception" },
  { id: "ctl-15", name: "Backup" },
  { id: "ctl-16", name: "Secure Deletion" },
];

const matrixMap: Record<string, ThreatMatrixEntry["status"]> = {
  "th-1-ctl-11": "implemented",
  "th-1-ctl-4": "partial",
  "th-1-ctl-12": "partial",
  "th-2-ctl-1": "implemented",
  "th-2-ctl-2": "implemented",
  "th-2-ctl-3": "implemented",
  "th-2-ctl-14": "partial",
  "th-3-ctl-8": "implemented",
  "th-3-ctl-9": "implemented",
  "th-3-ctl-10": "partial",
  "th-3-ctl-12": "implemented",
  "th-4-ctl-13": "implemented",
  "th-4-ctl-8": "partial",
  "th-4-ctl-10": "partial",
  "th-5-ctl-3": "implemented",
  "th-5-ctl-14": "implemented",
  "th-5-ctl-6": "partial",
  "th-6-ctl-7": "partial",
  "th-6-ctl-9": "implemented",
  "th-6-ctl-14": "implemented",
  "th-7-ctl-15": "implemented",
  "th-7-ctl-10": "implemented",
  "th-7-ctl-12": "implemented",
  "th-8-ctl-9": "implemented",
  "th-8-ctl-10": "partial",
  "th-8-ctl-11": "partial",
  "th-9-ctl-13": "partial",
  "th-9-ctl-16": "partial",
  "th-9-ctl-4": "implemented",
};

const threatMatrix: ThreatMatrixEntry[] = threats.flatMap((threat) =>
  controls.map((control) => ({
    threatId: threat.id,
    controlId: control.id,
    status: matrixMap[`${threat.id}-${control.id}`] ?? (control.name === "Backup" && threat.name === "API Abuse"
      ? "not_applicable"
      : "missing"),
  })),
);

const simulations: SimulationScenario[] = [
  {
    id: "sim-1",
    title: "MFA olmadan kritik veriye erişim",
    description: "Kritik veri için MFA olmayan erişimi simüle eder.",
    targetModule: "Access Requests",
    expectedOutcome: "Deny veya step-up kararı ve event üretimi.",
    relatedControls: ["MFA", "IAM", "RBAC/ABAC"],
  },
  {
    id: "sim-2",
    title: "Mesai dışı export",
    description: "Mesai dışı export talebini Zero Trust ve SIEM akışına düşürür.",
    targetModule: "Events",
    expectedOutcome: "Policy violation ve suspicious export olayları oluşur.",
    relatedControls: ["DLP", "SOAR"],
  },
  {
    id: "sim-3",
    title: "Public cloud'da şifrelenmemiş hassas veri",
    description: "Encryption ve KMS eksikliğini kritik bulguya çevirir.",
    targetModule: "Data Assets",
    expectedOutcome: "Risk skoru artar, compliance skoru düşer.",
    relatedControls: ["Encryption", "KMS", "CSPM"],
  },
  {
    id: "sim-4",
    title: "Deception bucket erişimi",
    description: "Sahte depoya erişim ile deception_triggered olayı üretir.",
    targetModule: "Deception",
    expectedOutcome: "Identity suspicious olur ve dashboard metriği güncellenir.",
    relatedControls: ["Deception", "SOAR", "SIEM"],
  },
  {
    id: "sim-5",
    title: "Üçüncü taraf API anahtarı anomalisi",
    description: "Third-party entegrasyon anomalisini üretir.",
    targetModule: "Events",
    expectedOutcome: "Token revoke önerisi oluşur.",
    relatedControls: ["CASB", "API Gateway"],
  },
  {
    id: "sim-6",
    title: "Ransomware davranış göstergesi",
    description: "Yoğun dosya değişikliği ve kurtarma hazırlığı akışını üretir.",
    targetModule: "Events",
    expectedOutcome: "Containment ve restore önerileri görünür.",
    relatedControls: ["Backup", "SOAR", "CWPP"],
  },
  {
    id: "sim-7",
    title: "İç kullanıcı yetki aşımı",
    description: "RBAC sınırını aşan erişim talebini oluşturur.",
    targetModule: "Policy Engine",
    expectedOutcome: "Unauthorized access event oluşur.",
    relatedControls: ["RBAC/ABAC", "IAM"],
  },
  {
    id: "sim-8",
    title: "API unrestricted resource consumption",
    description: "Rate limit aşımına yaklaşan kaynak tüketimini simüle eder.",
    targetModule: "Events",
    expectedOutcome: "API abuse ve throttling önerisi oluşur.",
    relatedControls: ["API Gateway", "CWPP"],
  },
  {
    id: "sim-9",
    title: "Loglama kapalı kaynak tespiti",
    description: "Visibility gap olayını üretir.",
    targetModule: "Compliance",
    expectedOutcome: "Detect skoru etkilenir.",
    relatedControls: ["SIEM", "CSPM"],
  },
  {
    id: "sim-10",
    title: "KVKK yurt dışı aktarım riski",
    description: "Kişisel veri içeren bir export akışını overseas transfer riskiyle işaretler.",
    targetModule: "Compliance",
    expectedOutcome: "Privacy risk event oluşur ve rapor katmanı güncellenir.",
    relatedControls: ["KVKK/GDPR", "CASB", "DLP"],
  },
];

const cloudNodes: CloudMapNode[] = [
  {
    id: "node-users",
    label: "Users",
    kind: "user",
    riskLevel: "medium",
    description: "Kurumsal kullanıcılar, analistler ve yöneticiler bu katmanda temsil edilir.",
    relatedAssetIds: ["asset-customer-db", "asset-governance-register"],
    relatedEventIds: events.filter((event) => event.source.includes("Emre") || event.source.includes("Ayse")).map((event) => event.id),
    recommendedControls: ["IAM", "MFA", "RBAC/ABAC"],
  },
  {
    id: "node-devices",
    label: "Devices",
    kind: "device",
    riskLevel: "medium",
    description: "Trusted, managed, unknown ve compromised cihaz bağlamı burada değerlendirilir.",
    relatedAssetIds: [],
    relatedEventIds: [],
    recommendedControls: ["CWPP", "MFA"],
  },
  {
    id: "node-iam",
    label: "IAM",
    kind: "security",
    riskLevel: "medium",
    description: "Kimlik doğrulama, rol yönetimi ve sürekli doğrulama sinyalleri.",
    relatedAssetIds: ["asset-secrets-vault"],
    relatedEventIds: events.filter((event) => event.relatedControl.includes("IAM")).map((event) => event.id),
    recommendedControls: ["IAM", "MFA", "RBAC/ABAC"],
  },
  {
    id: "node-zta",
    label: "Zero Trust Policy Engine",
    kind: "security",
    riskLevel: "low",
    description: "Policy Engine, Policy Administrator ve PEP akışı burada temsil edilir.",
    relatedAssetIds: ["asset-customer-db", "asset-finance-records"],
    relatedEventIds: events.filter((event) => event.relatedControl.includes("Zero Trust")).map((event) => event.id),
    recommendedControls: ["RBAC/ABAC", "MFA", "SIEM"],
  },
  {
    id: "node-api",
    label: "API Gateway",
    kind: "security",
    riskLevel: "medium",
    description: "API tüketim kontrolü, rate limiting ve OWASP API Security kontrolleri.",
    relatedAssetIds: ["asset-api-audit-logstore", "asset-vendor-sync-cache"],
    relatedEventIds: events.filter((event) => event.relatedControl.includes("API Gateway")).map((event) => event.id),
    recommendedControls: ["API Gateway", "CASB", "CWPP"],
  },
  {
    id: "node-private",
    label: "Private Cloud",
    kind: "cloud",
    riskLevel: "medium",
    description: "Kritik veri kümeleri ve policy-aware uygulama katmanı.",
    relatedAssetIds: assets.filter((asset) => asset.location === "private_cloud").map((asset) => asset.id),
    relatedEventIds: events.filter((event) => ["customer-db", "finance-records"].some((name) => event.target.includes(name))).map((event) => event.id),
    recommendedControls: ["Microsegmentation", "IAM", "SIEM"],
  },
  {
    id: "node-public",
    label: "Public Cloud",
    kind: "cloud",
    riskLevel: "high",
    description: "Analitik ve operasyon telemetrisi için kullanılan genel bulut katmanı.",
    relatedAssetIds: assets.filter((asset) => asset.location === "public_cloud").map((asset) => asset.id),
    relatedEventIds: events.filter((event) => event.target.includes("analytics") || event.target.includes("ops-telemetry")).map((event) => event.id),
    recommendedControls: ["CSPM", "CWPP", "API Gateway"],
  },
  {
    id: "node-saas",
    label: "SaaS",
    kind: "cloud",
    riskLevel: "high",
    description: "CRM ve onboarding export akışlarının bulunduğu SaaS alanı.",
    relatedAssetIds: assets.filter((asset) => asset.location === "saas").map((asset) => asset.id),
    relatedEventIds: events.filter((event) => event.target.includes("crm") || event.target.includes("vendor")).map((event) => event.id),
    recommendedControls: ["CASB", "DLP", "MFA"],
  },
  {
    id: "node-backup",
    label: "Backup Archive",
    kind: "data",
    riskLevel: "low",
    description: "Recover ve retention politikalarının toplandığı yedek katmanı.",
    relatedAssetIds: assets.filter((asset) => asset.location === "backup").map((asset) => asset.id),
    relatedEventIds: events.filter((event) => event.target.includes("archive") || event.target.includes("backup")).map((event) => event.id),
    recommendedControls: ["Backup", "Secure Deletion"],
  },
  {
    id: "node-deception",
    label: "Deception Storage",
    kind: "deception",
    riskLevel: "critical",
    description: "MITRE Engage mantığıyla tasarlanan sahte depolama ve adversary engagement katmanı.",
    relatedAssetIds: assets.filter((asset) => asset.location === "deception").map((asset) => asset.id),
    relatedEventIds: events.filter((event) => event.category === "deception_triggered").map((event) => event.id),
    recommendedControls: ["Deception", "SIEM", "SOAR"],
  },
  {
    id: "node-siem",
    label: "SIEM / SOAR",
    kind: "security",
    riskLevel: "medium",
    description: "Olay korelasyonu, playbook ve containment aksiyonları.",
    relatedAssetIds: [],
    relatedEventIds: events.map((event) => event.id),
    recommendedControls: ["SIEM", "SOAR"],
  },
  {
    id: "node-compliance",
    label: "Compliance Layer",
    kind: "compliance",
    riskLevel: "medium",
    description: "NIST CSF 2.0, ISO 27001, KVKK ve GDPR görünürlüğü bu katmanda toplanır.",
    relatedAssetIds: assets.filter((asset) => asset.kvkkScope || asset.gdprScope).map((asset) => asset.id),
    relatedEventIds: events.filter((event) => event.target.includes("contract") || event.relatedControl.includes("Governance")).map((event) => event.id),
    recommendedControls: ["Governance", "DLP", "Secure Deletion"],
  },
];

const cloudLinks: CloudMapLink[] = [
  { id: "ln-1", from: "node-users", to: "node-devices", tone: "safe", label: "Access context" },
  { id: "ln-2", from: "node-devices", to: "node-iam", tone: "safe", label: "Identity posture" },
  { id: "ln-3", from: "node-iam", to: "node-zta", tone: "safe", label: "Policy input" },
  { id: "ln-4", from: "node-zta", to: "node-api", tone: "warning", label: "API decision" },
  { id: "ln-5", from: "node-zta", to: "node-private", tone: "safe", label: "Least privilege" },
  { id: "ln-6", from: "node-zta", to: "node-public", tone: "warning", label: "High exposure" },
  { id: "ln-7", from: "node-zta", to: "node-saas", tone: "warning", label: "Third-party access" },
  { id: "ln-8", from: "node-zta", to: "node-backup", tone: "safe", label: "Recovery path" },
  { id: "ln-9", from: "node-zta", to: "node-deception", tone: "deception", label: "Adversary engagement" },
  { id: "ln-10", from: "node-private", to: "node-siem", tone: "safe", label: "Telemetry" },
  { id: "ln-11", from: "node-public", to: "node-siem", tone: "critical", label: "Critical finding" },
  { id: "ln-12", from: "node-saas", to: "node-siem", tone: "warning", label: "Anomaly feed" },
  { id: "ln-13", from: "node-deception", to: "node-siem", tone: "deception", label: "Critical alarm" },
  { id: "ln-14", from: "node-siem", to: "node-compliance", tone: "safe", label: "Control evidence" },
];

const demoSteps = [
  {
    id: "demo-1",
    title: "Hibrit bulut veri varlıkları gösterilir",
    description:
      "private-cloud/customer-db, public-cloud/analytics-bucket, private-cloud/finance-records, saas/crm-export, backup/cold-archive ve deception/admin-secrets-bucket görünür olur.",
    status: "pending" as const,
  },
  {
    id: "demo-2",
    title: "Kritik müşteri verisine mesai dışı export denemesi",
    description: "MFA olmadan export talebi oluşturulur.",
    status: "pending" as const,
  },
  {
    id: "demo-3",
    title: "Zero Trust analizi",
    description: "Kimlik, MFA, cihaz, veri hassasiyeti, zaman ve lokasyon birlikte değerlendirilir.",
    status: "pending" as const,
  },
  {
    id: "demo-4",
    title: "Karar SIEM olayına dönüşür",
    description: "Policy Engine kararı Event Center'a düşer.",
    status: "pending" as const,
  },
  {
    id: "demo-5",
    title: "SOAR aksiyonları önerilir",
    description: "Require MFA, revoke token, notify security team ve create ticket önerilir.",
    status: "pending" as const,
  },
  {
    id: "demo-6",
    title: "Şüpheli servis hesabı deception storage'a yönelir",
    description: "Aynı servis hesabı admin-secrets-bucket hedefine erişmeyi dener.",
    status: "pending" as const,
  },
  {
    id: "demo-7",
    title: "Deception alarmı tetiklenir",
    description: "Critical deception_triggered olayı oluşur ve isolate_identity önerilir.",
    status: "pending" as const,
  },
  {
    id: "demo-8",
    title: "Dashboard risk durumu güncellenir",
    description: "Genel güvenlik skoru düşer, kritik olay sayısı artar.",
    status: "pending" as const,
  },
  {
    id: "demo-9",
    title: "Compliance skorları etkilenir",
    description: "Detect ve Respond skorları yeni olaylarla yeniden hesaplanır.",
    status: "pending" as const,
  },
  {
    id: "demo-10",
    title: "Operasyon olay raporu oluşur",
    description: "Reports sayfasında operasyon akışını özetleyen olay raporu oluşturulur.",
    status: "pending" as const,
  },
];

export function createMockEnvironment(): DemoEnvironment {
  const withoutDerived = {
    assets,
    identities: seededIdentities,
    accessRequests,
    policyRules,
    events,
    deceptions: seededDeceptions,
    threats,
    controls,
    threatMatrix,
    simulations,
    layers,
    runs: [
      {
        id: makeId("run"),
        scenarioId: "sim-4",
        summary: "finance-batch-svc deception storage üzerinde alarm üretti.",
        createdAt: "2026-05-05T03:41:00.000Z",
        generatedEventIds: [seededDeception.event.id],
      },
    ],
    reports: [],
    demoScenario: {
      active: false,
      currentStep: 0,
      steps: demoSteps,
    },
    cloudNodes,
    cloudLinks,
  };

  const compliance = calculateComplianceSnapshot(withoutDerived);
  const withCompliance = {
    ...withoutDerived,
    compliance,
  };

  return {
    ...withCompliance,
    reports: generateReports(withCompliance),
  };
}
