import "server-only";

import { randomUUID } from "node:crypto";

import type {
  SecurityTestLaunchInput,
  SecurityTestLaunchResult,
  SecurityTestProviderFinding,
  SecurityTestProviderRuntime,
} from "@/server/services/security-testing/providers/security-test-provider";

function buildDemoFindings(input: SecurityTestLaunchInput): SecurityTestProviderFinding[] {
  const resource = input.target.target;
  const surfaceLabel =
    input.target.targetType === "repository"
      ? "repository authorization boundary"
      : input.target.targetType === "api"
        ? "API access-control boundary"
        : "web application session boundary";

  return [
    {
      externalId: `demo-${input.runId}-access-control`,
      title: "[Demo] Authorization boundary requires validation",
      severity: "high",
      category: "access_control_validation",
      description: `Synthetic validation signal for the ${surfaceLabel}. No exploit or live request was executed.`,
      evidence: [
        "Generated by the HCSC safe demo provider.",
        `Declared scope contains ${input.target.scope.length} entry or entries.`,
        "A real Strix runner must independently validate this control before remediation is accepted.",
      ],
      remediation: "Run an authorized isolated assessment, validate object-level authorization, and attach verified evidence.",
      affectedResource: resource,
      cvssScore: 7.4,
      pocAvailable: false,
      isSynthetic: true,
      metadata: {
        provider: "demo",
        scanMode: input.scanMode,
      },
    },
    {
      externalId: `demo-${input.runId}-scope`,
      title: "[Demo] Security test scope baseline recorded",
      severity: "info",
      category: "scope_governance",
      description: "Authorization, target scope, exclusions, budget and turn limits were captured successfully.",
      evidence: [
        `Environment: ${input.target.environment}`,
        `Budget cap: ${input.maxBudgetUsd ?? "not supplied"}`,
        `Turn cap: ${input.maxTurns}`,
      ],
      remediation: "Keep the authorization reference current and review exclusions before enabling a live provider.",
      affectedResource: resource,
      cvssScore: null,
      pocAvailable: false,
      isSynthetic: true,
      metadata: {
        provider: "demo",
      },
    },
  ];
}

export const demoSecurityTestProvider: SecurityTestProviderRuntime = {
  mode: "demo",
  ready: true,
  label: "Safe Demo Provider",
  description: "No network traffic, exploit or target mutation is performed. Results are synthetic and visibly labeled.",
  attribution: "HCSC safe simulation; Strix-compatible provider boundary",
  async launch(input): Promise<SecurityTestLaunchResult> {
    return {
      externalRunId: `hcsc-demo-${randomUUID()}`,
      status: "completed",
      summary: "Safe demo validation completed without contacting the target.",
      findings: buildDemoFindings(input),
      costUsd: 0,
      metadata: {
        synthetic: true,
        contactedTarget: false,
      },
    };
  },
};
