"use client";

import { type ReactNode, useMemo, useState } from "react";
import { Settings2Icon, ShieldCheckIcon, UserCircle2Icon } from "lucide-react";

import { useDemo } from "@/components/layout/demo-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";

const inputClassName =
  "mt-2 h-10 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm text-[var(--text-primary)] outline-none transition focus:border-cyan-400/40";

const textareaClassName =
  "mt-2 min-h-[92px] w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-3 text-sm text-[var(--text-primary)] outline-none transition focus:border-cyan-400/40";

export function SettingsView() {
  const {
    currentUser,
    currentOrganization,
    auth,
    can,
    settingsBundle,
    operationLoading,
    updateRiskPolicy,
    updateReportBranding,
    updateOrganizationSettings,
  } = useDemo();

  const isSaving = Boolean(operationLoading.settings);
  const organizationInitial = useMemo(
    () => ({
      name: settingsBundle?.organization.name ?? currentOrganization.name,
      plan: settingsBundle?.organization.plan ?? currentOrganization.plan,
      region: settingsBundle?.organization.region ?? currentOrganization.region,
      cloudMode: settingsBundle?.organizationSettings?.cloudMode ?? "hybrid_cloud",
      complianceFrameworks: (
        settingsBundle?.organizationSettings?.complianceFrameworks ??
        settingsBundle?.organization.complianceFrameworks ??
        currentOrganization.complianceFrameworks
      ).join(", "),
    }),
    [currentOrganization.complianceFrameworks, currentOrganization.name, currentOrganization.plan, currentOrganization.region, settingsBundle],
  );
  const riskPolicyInitial = useMemo(
    () => ({
      criticalClassificationWeight: settingsBundle?.riskPolicy?.criticalClassificationWeight ?? 24,
      missingEncryptionWeight: settingsBundle?.riskPolicy?.missingEncryptionWeight ?? 18,
      publicCloudSensitiveWeight: settingsBundle?.riskPolicy?.publicCloudSensitiveWeight ?? 16,
      missingBackupWeight: settingsBundle?.riskPolicy?.missingBackupWeight ?? 10,
      noKmsWeight: settingsBundle?.riskPolicy?.noKmsWeight ?? 12,
      openCriticalEventWeight: settingsBundle?.riskPolicy?.openCriticalEventWeight ?? 14,
      deceptionTriggerWeight: settingsBundle?.riskPolicy?.deceptionTriggerWeight ?? 20,
    }),
    [settingsBundle],
  );
  const brandingInitial = useMemo(
    () => ({
      companyName: settingsBundle?.reportBranding?.companyName ?? currentOrganization.name,
      reportFooter:
        settingsBundle?.reportBranding?.reportFooter ?? "Generated by Hybrid Cloud Security Console",
      preparedByLabel: settingsBundle?.reportBranding?.preparedByLabel ?? "Prepared by HCSC",
      confidentialityLabel:
        settingsBundle?.reportBranding?.confidentialityLabel ?? "Internal / Thesis Prototype",
    }),
    [currentOrganization.name, settingsBundle],
  );

  if (!can("manage_settings")) {
    return (
      <Panel>
        <div className="rounded-2xl border border-amber-500/20 bg-amber-500/10 px-4 py-4 text-sm leading-6 text-amber-200">
          Bu aksiyon için <span className="font-semibold">Security Admin</span> rolü gerekir. Ayarlar sayfası şu anda
          salt okunur erişim dışında kapalıdır.
        </div>
      </Panel>
    );
  }

  return (
    <div className="grid gap-4 xl:grid-cols-[0.9fr,1.1fr]">
      <div className="grid gap-4">
        <Panel>
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
              <UserCircle2Icon className="size-5 text-[var(--text-secondary)]" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">Profile</p>
              <h1 className="text-2xl font-semibold text-[var(--text-primary)]">{currentUser?.name}</h1>
            </div>
          </div>

          <div className="mt-5 grid gap-3 sm:grid-cols-2">
            <Metric label="E-posta" value={currentUser?.email ?? "—"} />
            <Metric label="Rol" value={currentUser?.role ?? "—"} />
            <Metric label="Departman" value={currentUser?.department ?? "—"} />
            <Metric label="Son giriş" value={auth.lastLoginAt ?? "—"} />
          </div>
        </Panel>

        <Panel>
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
              <ShieldCheckIcon className="size-5 text-cyan-300" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">Security</p>
              <h2 className="text-xl font-semibold text-[var(--text-primary)]">Oturum güvenliği</h2>
            </div>
          </div>

          <div className="mt-5 flex flex-wrap gap-2">
            <Badge variant="outline">{auth.isAuthenticated ? "Authenticated" : "Signed out"}</Badge>
            <Badge variant="outline">{auth.is2FAVerified ? "2FA verified" : "2FA pending"}</Badge>
            <Badge variant="outline">{currentUser?.mfaEnabled ? "MFA enabled" : "MFA disabled"}</Badge>
          </div>
        </Panel>

        <Panel>
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
              <Settings2Icon className="size-5 text-[var(--text-secondary)]" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">Organization</p>
              <h2 className="text-xl font-semibold text-[var(--text-primary)]">{currentOrganization.name}</h2>
            </div>
          </div>

          <div className="mt-5 grid gap-4">
            <OrganizationEditor
              key={JSON.stringify(organizationInitial)}
              initial={organizationInitial}
              isSaving={isSaving}
              onSave={updateOrganizationSettings}
            />
          </div>
        </Panel>
      </div>

      <div className="grid gap-4">
        <Panel>
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">Risk Policy</p>
              <h2 className="text-xl font-semibold text-[var(--text-primary)]">Risk ağırlıkları</h2>
            </div>
            <Badge variant="outline">DB-backed</Badge>
          </div>

          <RiskPolicyEditor
            key={JSON.stringify(riskPolicyInitial)}
            initial={riskPolicyInitial}
            isSaving={isSaving}
            onSave={updateRiskPolicy}
          />
        </Panel>

        <Panel>
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--text-muted)]">Report Branding</p>
              <h2 className="text-xl font-semibold text-[var(--text-primary)]">Rapor görünümü</h2>
            </div>
            <Badge variant="outline">Audit logged</Badge>
          </div>

          <ReportBrandingEditor
            key={JSON.stringify(brandingInitial)}
            initial={brandingInitial}
            isSaving={isSaving}
            onSave={updateReportBranding}
          />
        </Panel>
      </div>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4">
      <p className="text-xs uppercase tracking-[0.16em] text-[var(--text-muted)]">{label}</p>
      <p className="mt-2 text-sm font-medium text-[var(--text-primary)]">{value}</p>
    </div>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="block">
      <p className="text-xs uppercase tracking-[0.16em] text-[var(--text-muted)]">{label}</p>
      {children}
    </label>
  );
}

function OrganizationEditor({
  initial,
  isSaving,
  onSave,
}: {
  initial: {
    name: string;
    plan: string;
    region: string;
    cloudMode: "private_cloud" | "public_cloud" | "hybrid_cloud";
    complianceFrameworks: string;
  };
  isSaving: boolean;
  onSave: (payload: {
    name?: string;
    plan?: string;
    region?: string;
    cloudMode?: "private_cloud" | "public_cloud" | "hybrid_cloud";
    complianceFrameworks?: string[];
  }) => Promise<void>;
}) {
  const [form, setForm] = useState(initial);
  const frameworkPreview = useMemo(
    () =>
      form.complianceFrameworks
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    [form.complianceFrameworks],
  );

  return (
    <>
      <Field label="Organization Name">
        <input
          className={inputClassName}
          value={form.name}
          onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))}
        />
      </Field>
      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Plan">
          <input
            className={inputClassName}
            value={form.plan}
            onChange={(event) => setForm((current) => ({ ...current, plan: event.target.value }))}
          />
        </Field>
        <Field label="Region">
          <input
            className={inputClassName}
            value={form.region}
            onChange={(event) => setForm((current) => ({ ...current, region: event.target.value }))}
          />
        </Field>
      </div>
      <Field label="Cloud Mode">
        <select
          className={inputClassName}
          value={form.cloudMode}
          onChange={(event) =>
            setForm((current) => ({
              ...current,
              cloudMode: event.target.value as typeof current.cloudMode,
            }))
          }
        >
          <option value="private_cloud">Private Cloud</option>
          <option value="public_cloud">Public Cloud</option>
          <option value="hybrid_cloud">Hybrid Cloud</option>
        </select>
      </Field>
      <Field label="Compliance Frameworks">
        <textarea
          className={textareaClassName}
          value={form.complianceFrameworks}
          onChange={(event) => setForm((current) => ({ ...current, complianceFrameworks: event.target.value }))}
        />
      </Field>
      <div className="flex flex-wrap gap-2">
        {frameworkPreview.map((framework) => (
          <Badge key={framework} variant="outline">
            {framework}
          </Badge>
        ))}
      </div>
      <div className="flex justify-end">
        <Button
          disabled={isSaving}
          onClick={() =>
            void onSave({
              name: form.name,
              plan: form.plan,
              region: form.region,
              cloudMode: form.cloudMode,
              complianceFrameworks: frameworkPreview,
            })
          }
        >
          {isSaving ? "Kaydediliyor..." : "Organization Kaydet"}
        </Button>
      </div>
    </>
  );
}

function RiskPolicyEditor({
  initial,
  isSaving,
  onSave,
}: {
  initial: {
    criticalClassificationWeight: number;
    missingEncryptionWeight: number;
    publicCloudSensitiveWeight: number;
    missingBackupWeight: number;
    noKmsWeight: number;
    openCriticalEventWeight: number;
    deceptionTriggerWeight: number;
  };
  isSaving: boolean;
  onSave: (payload: {
    criticalClassificationWeight: number;
    missingEncryptionWeight: number;
    publicCloudSensitiveWeight: number;
    missingBackupWeight: number;
    noKmsWeight: number;
    openCriticalEventWeight: number;
    deceptionTriggerWeight: number;
  }) => Promise<void>;
}) {
  const [form, setForm] = useState(initial);

  return (
    <>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">
        {Object.entries(form).map(([key, value]) => (
          <Field key={key} label={key}>
            <input
              type="number"
              min={0}
              max={100}
              className={inputClassName}
              value={value}
              onChange={(event) =>
                setForm((current) => ({
                  ...current,
                  [key]: Number(event.target.value),
                }))
              }
            />
          </Field>
        ))}
      </div>

      <div className="mt-5 flex justify-end">
        <Button disabled={isSaving} onClick={() => void onSave(form)}>
          {isSaving ? "Kaydediliyor..." : "Risk Policy Kaydet"}
        </Button>
      </div>
    </>
  );
}

function ReportBrandingEditor({
  initial,
  isSaving,
  onSave,
}: {
  initial: {
    companyName: string;
    reportFooter: string;
    preparedByLabel: string;
    confidentialityLabel: string;
  };
  isSaving: boolean;
  onSave: (payload: {
    companyName: string;
    reportFooter: string;
    preparedByLabel: string;
    confidentialityLabel: string;
  }) => Promise<void>;
}) {
  const [form, setForm] = useState(initial);

  return (
    <>
      <div className="mt-5 grid gap-4">
        <Field label="Company Name">
          <input
            className={inputClassName}
            value={form.companyName}
            onChange={(event) => setForm((current) => ({ ...current, companyName: event.target.value }))}
          />
        </Field>
        <Field label="Prepared By Label">
          <input
            className={inputClassName}
            value={form.preparedByLabel}
            onChange={(event) => setForm((current) => ({ ...current, preparedByLabel: event.target.value }))}
          />
        </Field>
        <Field label="Confidentiality Label">
          <input
            className={inputClassName}
            value={form.confidentialityLabel}
            onChange={(event) => setForm((current) => ({ ...current, confidentialityLabel: event.target.value }))}
          />
        </Field>
        <Field label="Report Footer">
          <textarea
            className={textareaClassName}
            value={form.reportFooter}
            onChange={(event) => setForm((current) => ({ ...current, reportFooter: event.target.value }))}
          />
        </Field>
      </div>

      <div className="mt-5 flex justify-end">
        <Button disabled={isSaving} onClick={() => void onSave(form)}>
          {isSaving ? "Kaydediliyor..." : "Branding Kaydet"}
        </Button>
      </div>
    </>
  );
}
